LINK_TYPE_IMAGE = 10
LINK_TYPE_PROFILE = 20

HOUSING_LINK_TYPES = {
    (LINK_TYPE_IMAGE, "Image"),
    (LINK_TYPE_PROFILE, "Profile")
}


CONTENT_STATE_ORIGINAL = 10
CONTENT_STATE_TRANSLATED = 20

CONTENT_STATES = {
    (CONTENT_STATE_ORIGINAL, "Original"),
    (CONTENT_STATE_TRANSLATED, "Translated")
}

