# Generated by Django 2.2.2 on 2019-06-26 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrientSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('unit', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=2048)),
                ('modifier', models.CharField(max_length=2048)),
                ('weight', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Food')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.MeasureUnit')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrientDerivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodNutrientSource')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('derivation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodNutrientDerivation')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='FoodLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodLogCategory')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Food')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodPortion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodCategory'),
        ),
    ]
