# Generated by Django 2.2.2 on 2019-06-26 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtrack', '0002_delete_foodlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodLogCategory')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Food')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodPortion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
