# Generated by Django 2.2.2 on 2019-06-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0003_foodlogentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodportion',
            old_name='weight',
            new_name='gram_weight',
        ),
    ]
