# Generated by Django 2.2.2 on 2019-06-26 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtrack', '0004_auto_20190626_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('kind', models.IntegerField(choices=[(1, 'Daily Targets')])),
            ],
        ),
        migrations.RemoveField(
            model_name='foodlogentry',
            name='portion',
        ),
        migrations.AddField(
            model_name='foodlogentry',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.MeasureUnit'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodtrack.NutritionProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionProfileTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('notes', models.TextField(null=True)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Nutrient')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.NutritionProfile')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('amount', models.FloatField()),
                ('notes', models.TextField(null=True)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Nutrient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLogEntryNutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.FoodLogEntry')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Nutrient')),
            ],
        ),
    ]
