# Generated by Django 2.2.2 on 2019-06-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0007_auto_20190630_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlogentry',
            name='unit',
        ),
        migrations.AddField(
            model_name='foodlogentry',
            name='portion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodtrack.FoodPortion'),
        ),
        migrations.AlterField(
            model_name='foodlogentry',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Food'),
        ),
    ]
