# Generated by Django 2.2.2 on 2019-06-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0008_auto_20190630_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodLogEntryNutrients',
            new_name='FoodLogEntryNutrient',
        ),
        migrations.DeleteModel(
            name='RecentSelection',
        ),
    ]
