# Generated by Django 2.2.2 on 2019-07-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0009_auto_20190630_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=1024, null=True)),
                ('rate', models.FloatField()),
                ('rate_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(20, 'Other'), (10, 'Food from DB')])),
                ('amount', models.FloatField(null=True)),
                ('cost', models.FloatField()),
                ('dt', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Currency')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodtrack.MeasureUnit')),
            ],
        ),
    ]
