# Generated by Django 2.2.2 on 2019-07-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0009_auto_20190630_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutritionProfileTargets',
            new_name='NutritionProfileTarget',
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Daily Targets'), (10, 'Daily Ratios')]),
        ),
    ]
