# Generated by Django 2.2.2 on 2019-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0012_auto_20190701_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='pcs',
            field=models.IntegerField(default=None, null=True, verbose_name='Pieces'),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('sample_food', 'sample_food'), ('foundation_food', 'foundation_food'), ('sr_legacy_food', 'sr_legacy_food'), ('sub_sample_food', 'sub_sample_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('branded_food', 'branded_food'), ('market_acquisition', 'market_acquisition'), ('survey_fndds_food', 'survey_fndds_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Other'), (10, 'Food from DB')]),
        ),
    ]
