# Generated by Django 2.2.2 on 2019-07-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0010_auto_20190701_1135'),
        ('foodtrack', '0013_auto_20190701_1535'),
    ]

    operations = [
    ]
