# Generated by Django 2.2.2 on 2019-07-01 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtrack', '0016_auto_20190701_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nutrienttargets',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Daily Grams'), (20, 'Daily Percentage')], default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('sample_food', 'sample_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('foundation_food', 'foundation_food'), ('branded_food', 'branded_food'), ('market_acquisition', 'market_acquisition'), ('sr_legacy_food', 'sr_legacy_food'), ('survey_fndds_food', 'survey_fndds_food'), ('sub_sample_food', 'sub_sample_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Daily Targets'), (10, 'Future Implementation')]),
        ),
        migrations.AlterField(
            model_name='nutritionprofiletarget',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Daily Grams'), (20, 'Daily Percentage')]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Other'), (10, 'Food from DB')]),
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('custom_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Recipe')),
                ('food', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodtrack.Food')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodtrack.MeasureUnit')),
            ],
        ),
    ]
