# Generated by Django 2.2.2 on 2019-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0018_auto_20190701_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(30, 'Other'), (10, 'Volume'), (20, 'Weight')], default=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('sub_sample_food', 'sub_sample_food'), ('foundation_food', 'foundation_food'), ('sample_food', 'sample_food'), ('market_acquisition', 'market_acquisition'), ('agricultural_acquisition', 'agricultural_acquisition'), ('sr_legacy_food', 'sr_legacy_food'), ('survey_fndds_food', 'survey_fndds_food'), ('branded_food', 'branded_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Food from DB'), (20, 'Other')]),
        ),
    ]
