# Generated by Django 2.2.2 on 2019-07-02 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0019_auto_20190702_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('sub_sample_food', 'sub_sample_food'), ('branded_food', 'branded_food'), ('foundation_food', 'foundation_food'), ('market_acquisition', 'market_acquisition'), ('sr_legacy_food', 'sr_legacy_food'), ('survey_fndds_food', 'survey_fndds_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('sample_food', 'sample_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Weight'), (10, 'Volume'), (30, 'Other')], default=30),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField()),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.MeasureUnit')),
            ],
        ),
    ]
