# Generated by Django 2.2.2 on 2019-07-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0020_auto_20190702_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('market_acquisition', 'market_acquisition'), ('sample_food', 'sample_food'), ('foundation_food', 'foundation_food'), ('branded_food', 'branded_food'), ('sub_sample_food', 'sub_sample_food'), ('survey_fndds_food', 'survey_fndds_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('sr_legacy_food', 'sr_legacy_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(30, 'Other'), (10, 'Volume'), (20, 'Weight')], default=30),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='ratio',
            field=models.FloatField(default=None, null=True),
        ),
    ]
