# Generated by Django 2.2.2 on 2019-07-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0021_auto_20190702_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecomponent',
            name='unit',
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='portion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodtrack.FoodPortion'),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('sr_legacy_food', 'sr_legacy_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('survey_fndds_food', 'survey_fndds_food'), ('sample_food', 'sample_food'), ('branded_food', 'branded_food'), ('sub_sample_food', 'sub_sample_food'), ('foundation_food', 'foundation_food'), ('market_acquisition', 'market_acquisition')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Weight'), (30, 'Other'), (10, 'Volume')], default=30),
        ),
        migrations.AlterField(
            model_name='nutrienttargets',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Daily Percentage'), (10, 'Daily Grams')]),
        ),
        migrations.AlterField(
            model_name='nutritionprofiletarget',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Daily Percentage'), (10, 'Daily Grams')]),
        ),
    ]
