# Generated by Django 2.2.2 on 2019-07-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0022_auto_20190702_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='serving_size',
        ),
        migrations.AddField(
            model_name='foodlogentry',
            name='alt_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Recipe'),
        ),
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('foundation_food', 'foundation_food'), ('market_acquisition', 'market_acquisition'), ('sr_legacy_food', 'sr_legacy_food'), ('sub_sample_food', 'sub_sample_food'), ('branded_food', 'branded_food'), ('sample_food', 'sample_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('survey_fndds_food', 'survey_fndds_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Weight'), (10, 'Volume'), (30, 'Other')], default=30),
        ),
        migrations.AlterField(
            model_name='nutrienttargets',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Daily Grams'), (20, 'Daily Percentage')]),
        ),
        migrations.AlterField(
            model_name='nutritionprofiletarget',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Daily Grams'), (20, 'Daily Percentage')]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Other'), (10, 'Food from DB')]),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='foodtrack.Food'),
        ),
    ]
