# Generated by Django 2.2.2 on 2019-07-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0023_auto_20190702_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('market_acquisition', 'market_acquisition'), ('sr_legacy_food', 'sr_legacy_food'), ('foundation_food', 'foundation_food'), ('sample_food', 'sample_food'), ('sub_sample_food', 'sub_sample_food'), ('survey_fndds_food', 'survey_fndds_food'), ('branded_food', 'branded_food'), ('agricultural_acquisition', 'agricultural_acquisition')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Weight'), (30, 'Other'), (10, 'Volume')], default=30),
        ),
        migrations.AlterField(
            model_name='nutrienttargets',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Daily Percentage'), (10, 'Daily Grams')]),
        ),
        migrations.AlterField(
            model_name='nutritionprofiletarget',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Daily Percentage'), (10, 'Daily Grams')]),
        ),
    ]
