# Generated by Django 2.2.2 on 2019-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0025_auto_20190702_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('sr_legacy_food', 'sr_legacy_food'), ('foundation_food', 'foundation_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('branded_food', 'branded_food'), ('market_acquisition', 'market_acquisition'), ('sample_food', 'sample_food'), ('sub_sample_food', 'sub_sample_food'), ('survey_fndds_food', 'survey_fndds_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Food from DB'), (20, 'Other')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_gram',
            field=models.FloatField(default=None, null=True),
        ),
    ]
