# Generated by Django 2.2.2 on 2019-07-02 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtrack', '0026_auto_20190702_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodUsageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientUsageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=0)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Nutrient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('sample_food', 'sample_food'), ('foundation_food', 'foundation_food'), ('sub_sample_food', 'sub_sample_food'), ('branded_food', 'branded_food'), ('agricultural_acquisition', 'agricultural_acquisition'), ('survey_fndds_food', 'survey_fndds_food'), ('market_acquisition', 'market_acquisition'), ('sr_legacy_food', 'sr_legacy_food')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(30, 'Other'), (20, 'Weight'), (10, 'Volume')], default=30),
        ),
        migrations.DeleteModel(
            name='NutrientOrder',
        ),
        migrations.AddField(
            model_name='foodusagecounter',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrack.Food'),
        ),
        migrations.AddField(
            model_name='foodusagecounter',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
