# Generated by Django 2.2.2 on 2019-07-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0027_auto_20190702_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='data_type',
            field=models.CharField(choices=[('agricultural_acquisition', 'agricultural_acquisition'), ('foundation_food', 'foundation_food'), ('branded_food', 'branded_food'), ('sr_legacy_food', 'sr_legacy_food'), ('survey_fndds_food', 'survey_fndds_food'), ('sub_sample_food', 'sub_sample_food'), ('sample_food', 'sample_food'), ('market_acquisition', 'market_acquisition')], max_length=2048),
        ),
        migrations.AlterField(
            model_name='foodusagecounter',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='foodtrack.Food'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Volume'), (20, 'Weight'), (30, 'Other')], default=30),
        ),
        migrations.AlterField(
            model_name='nutrientusagecounter',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='foodtrack.Nutrient'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='kind',
            field=models.IntegerField(choices=[(20, 'Other'), (10, 'Food from DB')]),
        ),
    ]
